### ISSUE TITLE
Not Running Correctly

### ISSUE THREAD

**Issue by AviaCoconut** [Eurobertics/Nebucord#1]
I'm trying to run this but it's giving me issues.

`root@aeronus-webserver:/var/www/html/bot# php -f bot.php 
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Starting Nebucord v. 0.8.2 on nebucordws.nebulatien.org
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Starting HTTP client...
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Eventtable set...
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | No actiontable set, using default one...
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Connecting to Discord WebSocket gateway...
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | WebSocket connection established.
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Nebucord set up, entering main loop...
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Event received: READY - Sequence: 1
PHP Notice:  Undefined index: ctrlusr in /var/www/html/bot/vendor/eurobertics/nebucord/src/Controller/Nebucord_RuntimeController.php on line 272
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Event received:  - Sequence: 
29-12-2019 01:24:18 - nebucordws.nebulatien.org - warn | Creating default model, no appropriate model for event found.
PHP Notice:  Undefined offset: 0 in /var/www/html/bot/vendor/eurobertics/nebucord/src/Controller/Nebucord_EventController.php on line 135
PHP Notice:  Undefined offset: 0 in /var/www/html/bot/vendor/eurobertics/nebucord/src/Controller/Nebucord_EventController.php on line 135
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/html/
bot/vendor/eurobertics/nebucord/src/Controller/Nebucord_EventController.php on line 135
29-12-2019 01:24:18 - nebucordws.nebulatien.org - info | Event received:  - Sequence: `

**Comment by AviaCoconut** [comment]
^ PHP7.0

`<?php
include "vendor/autoload.php";

use Nebucord\Nebucord;

$nebucord = new Nebucord(['token' => 'REMOVED']);
$nebucord->bootstrap()->run();`

**Comment by Eurobertics** [comment]
I'm sorry for My late delay.
As far as I can see, and this may be My fault, but the documentation is missing a parameter wich I added after the docs are written.

You are missing the control-user. The user wich can issue control commands to the bot.

Just try this:

```php
$nebucord = new Nebucord(['token' => 'REMOVED', 'ctrlusr' => ['1234567890']]);
$nebucord->bootstrap()->setEventTable()->run();
```

As you can see, the second array key ```ctrlusr``` is also an array with the snowflake of the user(s) who can control the bot. This should obvisiously be your account snowflake.

If you have further issues, please let Me know. I'll be here.

I'll updating the docs immediately.

Sry again for My late response.
