### ISSUE TITLE
Don't hardcode LOGFILE_PATH

### ISSUE THREAD

**Issue by iggyvolz** [Eurobertics/Nebucord#2]
Not all servers run on apache, and /var/log/apache2 is not always an appropriate place for log files.  If the directory doesn't exist, the program crashes  Nebucord_Logger should take a log directory as a parameter.

**Comment by Eurobertics** [comment]
True, I'll fix this in the next version (this will happen very soon). This is also an issue with the (new) Docker image where also Apache2 is not installed.
It came from an older deployment where mostly Apache was installed because of the REST part of Nebucord.
Sorry for the late delay.

**Comment by Eurobertics** [comment]
As for now I only changed the directory to ```/var/log/```. The reason is, that in an near future the whole logging part will be replaced with logging and exceptions.

This is more a compatibility fix.

The fix is available in [v0.8.5](https://github.com/Eurobertics/Nebucord/releases/tag/v0.8.5)
