### ISSUE TITLE
Nebucord threading

### ISSUE THREAD

**Issue by bitnykk** [Eurobertics/Nebucord#5]
Hello,

I'm the maintainer of a PHP game chatbot named Bebot (forum @ bebot.shadow-realm.org) and i'm considering Nebucord as an API source candidate for a Discord module i'm planning soon.

But the problem is once i included Nebucord as a module and initiated its connection (bootstrap->run), my chatbot is 100% busy on the Nebucord websocket and doesn't respond anything else.

Would you see a flexible way to include Nebucord as child process while keeping the main thread available for other chatbot tasks ? I've been thinking of using PHP 7 pthreads but it would require full reinstall ...

Any suggestion is welcomed !

**Comment by Eurobertics** [comment]
Hi,
first let Me say sorry for my very delayed answer.

Sounds great if you considering this API as an module for your project, if this is still an actual case due to my late response.

Unfortunately you are right. Currently i have no optimizations implementd. It was not intended to run multithreaded. But
it is a nice idea to do it.
From an first look, i would say ```pthreads```  are the best way to go. But you could try ```pcntl_fork()``` to fork the Nebucord child into a sub process.
More information: [PHP: pcntl_fork - Manual](https://www.php.net/manual/en/function.pcntl-fork.php)
But i never tried this.

Cheers

**Comment by bitnykk** [comment]
Hello Bernd,

As i had to find a solution for a wide range of php version (5.4 upto 7.4) i couldn't implement "Nebucord", that is very nice by the way for PHP 7+ strictly.

 

I finally moved to a simple Curl oriented solution ("Kiss") for the Discord API part, that is working downto 5.2 even.
And for the Discord ping that validates bot permission, i went for "SimpleDiscord" that has fewest dependencies i found.

That said, "Nebucord" would have been my top choice if i would have needed a 100% Discord bot.
But in this project, bot has to connect to 1 among 2 games chat as main goal, and use Discord for a secondary relay.
Hence i was needing to multithread it as the bot has many others tasks to do out of Discord relay itself :)

Nice piece of code anyways, it was interesting to dive into for my preliminary tests :)

 

Thanks a lot for your kind reply, best regards,
BN


 

Envoyé: jeudi 11 mars 2021 à 15:24
De: "Bernd Robertz" ***@***.***>
À: "Eurobertics/Nebucord" ***@***.***>
Cc: "bitnykk" ***@***.***>, "Author" ***@***.***>
Objet: Re: [Eurobertics/Nebucord] Nebucord threading (#5)


 

Hi,
first let Me say sorry for my very delayed answer.

Sounds great if you considering this API as an module for your project, if this is still an actual case due to my late response.

Unfortunately you are right. Currently i have no optimizations implementd. It was not intended to run multithreaded. But
it is a nice idea to do it.
From an first look, i would say pthreads are the best way to go. But you could try pcntl_fork() to fork the Nebucord child into a sub process.
More information: PHP: pcntl_fork - Manual
But i never tried this.

Cheers

**Comment by Eurobertics** [comment]
Hi bitnykk,

thank you for your kind words. I'm very happy that you like Nebucord.

As far as i understand your project, your KISS implementation is a great solution.
But feel free to come back if you need something like Nebucord.

In the meantime, i'll taking multithreading to the feature request list, it is a quite good idea.

Cheers
