### ISSUE TITLE
TYPO

### ISSUE THREAD

**Issue by itcom** [Eurobertics/Nebucord#7]
https://github.com/Eurobertics/Nebucord/blob/baaaead62177812955b15aefe768cf966dc24a73/src/Base/StatusList.php#L115C19-L115C19

**Comment by Eurobertics** [comment]
First I'm very sorry for my late response. As usual the real live is hitting again and again :-)

Thank you for your issue, you are correct, there is a typeo. I'll fix this in the main branch ASAP. A new release will be also here soon.

**Comment by Eurobertics** [comment]
Fixed with [commit](https://github.com/Eurobertics/Nebucord/commit/134c4a33d7c71890c43f3d1a8b354fb23fdcf35b)
